name: Create a release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure tags are available
      - name: Determine release version
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            PRERELEASE=false
          else
            VERSION="dev-$(date +%Y%m%d%H%M)"
            PRERELEASE=true
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "prerelease=$PRERELEASE" >> $GITHUB_OUTPUT
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Prepare artifacts
        run: |
          mkdir -p dist
          mv msxtileforge-linux-x64-bin/*.deb dist
          zip --junk-paths \
            dist/msxtileforge-${{ steps.get_version.outputs.version }}-linux-x64-bin.zip \
            msxtileforge-linux-x64-bin/*
          zip --junk-paths \
            dist/msxtileforge-${{ steps.get_version.outputs.version }}-windows-x64-bin.zip \
            msxtileforge-windows-x64-bin/*
          zip --junk-paths \
            dist/msxtileforge-${{ steps.get_version.outputs.version }}-mac-x86_64-bin.zip \
            msxtileforge-mac-x86_64-bin/*
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: "Release ${{ steps.get_version.outputs.version }}"
          files: dist/*
          prerelease: ${{ steps.get_version.outputs.prerelease }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
